# Picture Perfect

Still in your role as a data analyst for a video streaming service, you have now been asked by your manager to compare and contrast the revenue numbers by quarter for the various international regions.

Be sure to consult the [HvPlot Customization](https://hvplot.holoviz.org/user_guide/Customization.html) page for additional opportunities of aesthetic improvement.

In [1]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path

## Step 1: Prepare the Regional Revenue DataFrame

In [15]:
# Read in regional_revenue.csv file into a Pandas DataFrame
regional_revenue_df = pd.read_csv("../Resources/regional_revenue.csv")

# Review the DataFrame
regional_revenue_df.head(10)

                             Area      Years     Revenue
0        United States and Canada  Q1 - 2018  1976157000
1  Europe, Middle East and Africa  Q1 - 2018   886649000
2                   Latin America  Q1 - 2018   540182000
3                    Asia-Pacific  Q1 - 2018   199117000
4        United States and Canada  Q2 - 2018  2049546000
5  Europe, Middle East and Africa  Q2 - 2018   975497000
6                   Latin America  Q2 - 2018   568071000
7                    Asia-Pacific  Q2 - 2018   221252000
8        United States and Canada  Q3 - 2018  2094850000
9  Europe, Middle East and Africa  Q3 - 2018  1004749000

## Step 2: Create a plot that visualizes the growth in revenue for the United States and Canada

In [18]:
# Create a DataFrame that slices the subscriber data for the United States and Canada
us_canada_revenue = regional_revenue_df[regional_revenue_df['Area'] == "United States and Canada"]

# Set the index of the DataFrame to Years
us_canada_revenue = us_canada_revenue.set_index('Years')

# Create a line plot of the US and Canada Revenue data
us_canada_revenue['Revenue'].hvplot()

:Curve   [Years]   (Revenue)

## Step 3: Add x- and y-axis labels to your plot. Rotate the x-axis plot ticks 45 degrees.

In [19]:
# Rotate the x-axis ticks by 45 degrees and add x- and y-axis labels to the plot
us_canada_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue")

:Curve   [Years]   (Revenue)

## Step 4:  Add a title to the US and Canada revenue plot

In [20]:
# Add a title to your US and Canada revenue plot using the label parameter
us_canada_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "US and Canada Revenue")

:Curve   [Years]   (Revenue)

## Step 5: Use the yformatter option to format the y-axis values.

In [21]:
# Use the yformatter to adjust the y-axis values
us_canada_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "US and Canada Revenue").opts(yformatter='%.0f')

:Curve   [Years]   (Revenue)

## Step 6: Add a line_color of blue and hover_line_color of yellow to the plot.

In [ ]:
# Add a line_color of blue and a hover_line_color of yellow
us_canada_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "US and Canada Revenue").opts(
    yformatter='%.0f', 
    color="blue", 
    hover_line_color="yellow")

:Curve   [Years]   (Revenue)

## Step 7. Save the plot you just created to a variable so that it can eventually be utilized in an overlay plot.

In [23]:
# Save the US and Canada revenue plot to a variable
us_canada_plot = us_canada_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "US and Canada Revenue").opts(
    yformatter='%.0f', 
    color="blue", 
    hover_line_color="yellow")

# Show the plot
us_canada_plot

:Curve   [Years]   (Revenue)

## Step 8: Create a line plot that visualizes the growth in revenue for the Europe, Middle East and Africa region. Style it with the same options utilized in the first plot. However, make the line_color equal to orange. Be sure to save this plot to a variable as well.

In [40]:
# Create a DataFrame that slices the subscriber data for the Europe, Middle East and Africa
emea_revenue = regional_revenue_df[regional_revenue_df['Area'] == "Europe, Middle East and Africa"]


# Set the index of the DataFrame to Years
emea_revenue = emea_revenue.set_index("Years")

In [41]:
# Create a styled line plot for the Europe, Middle East Africa region. 
# Make the line_color orange and be sure to set the plot equal to a variable. 
emea_plot = emea_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "EMEA Revenue").opts(
    yformatter='%.0f', 
    color="orange", 
    hover_line_color="yellow")

# Show the plot
emea_plot

:Curve   [Years]   (Revenue)

## Step 9: Create an overlay plot for the "United States and Canada" and the "Europe, Middle East and Africa" regions.

In [63]:
# Create an overlay plot for the two visualizations
combined = us_canada_plot * emea_plot 
type(combined)

holoviews.core.overlay.Overlay

## Step 10: Add a title to the overlay plot. Additionally, adjust height, width and background color.

In [65]:
# Adjust the title, height, width and background color of the overlay plot
from holoviews import opts

combined.opts(
    opts.Overlay(title="US and Canada vs Europe, Middle East, and Africa",
              frame_width=1000,
              frame_height= 300,
              bgcolor ='#f5f5f5')
)

:Overlay
   .Curve.US_and_Canada_Revenue :Curve   [Years]   (Revenue)
   .Curve.EMEA_Revenue          :Curve   [Years]   (Revenue)

## Step 11: Bonus - Create line plots for the Latin America and Asia Pacific Regions

In [66]:
regional_revenue_df.head(10)

                             Area      Years     Revenue
0        United States and Canada  Q1 - 2018  1976157000
1  Europe, Middle East and Africa  Q1 - 2018   886649000
2                   Latin America  Q1 - 2018   540182000
3                    Asia-Pacific  Q1 - 2018   199117000
4        United States and Canada  Q2 - 2018  2049546000
5  Europe, Middle East and Africa  Q2 - 2018   975497000
6                   Latin America  Q2 - 2018   568071000
7                    Asia-Pacific  Q2 - 2018   221252000
8        United States and Canada  Q3 - 2018  2094850000
9  Europe, Middle East and Africa  Q3 - 2018  1004749000

In [67]:
# Create a DataFrame that slices the subscriber data for the Asia-Pacific region
ap_revenue = regional_revenue_df[regional_revenue_df["Area"] == "Asia-Pacific"]

# Set the index of the DataFrame to Years
ap_revenue = ap_revenue.set_index('Years')

In [74]:
# Create a styled line plot for the Asia-Pacific region. 
# Make the line_color orange and be sure to set the plot equal to a variable. 
ap_plot = ap_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "Asia-Pacific Revenue").opts(
    yformatter='%.0f', 
    color="green", 
    hover_line_color="yellow")
# Show the plot
ap_plot

:Curve   [Years]   (Revenue)

In [69]:
# Create a DataFrame that slices the subscriber data for the Latin America region
lam_revenue = regional_revenue_df[regional_revenue_df["Area"] == "Latin America"]

# Set the index of the DataFrame to Years
lam_revenue = lam_revenue.set_index('Years')

In [75]:
# Create a styled line plot for the Latin America region. 
# Make the line_color orange and be sure to set the plot equal to a variable. 
lam_plot = lam_revenue['Revenue'].hvplot(rot=45, xlabel="Quarters", ylabel="Revenue", label = "Latin America Revenue").opts(
    yformatter='%.0f', 
    color="purple", 
    hover_line_color="yellow")

# Show the plot
lam_plot

:Curve   [Years]   (Revenue)

In [76]:
# Create a compose plot for all four regions

us_canada_plot * emea_plot * lam_plot * ap_plot

:Overlay
   .Curve.US_and_Canada_Revenue             :Curve   [Years]   (Revenue)
   .Curve.EMEA_Revenue                      :Curve   [Years]   (Revenue)
   .Curve.Latin_America_Revenue             :Curve   [Years]   (Revenue)
   .Curve.Asia_hyphen_minus_Pacific_Revenue :Curve   [Years]   (Revenue)